/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package p_pay.app;

import p_pay.list.LinkedList;

import static p_pay.utilities.StringUtils.join;
import static p_pay.utilities.StringUtils.split;
import static p_pay.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
